name = "cloudflare-wallet-app-provider"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "p3"
database_id = "2076a0d8-2914-4073-8bd1-08df6be04447"

[vars]
SPLICE_HOST = "p2.cantondefi.com"
SPLICE_PORT = 443
CANTON_JSON_HOST = "p2-json.cantondefi.com"
CANTON_JSON_PORT = 443
CANTON_AUTH_SECRET = ""
CANTON_AUTH_USER = "ledger-api-user"
SPLICE_ADMIN_USER = "app-user"
CANTON_AUTH_AUDIENCE = "https://canton.network.global"
RP_ID = "P2"
RP_NAME = "P2"
THEME = "teal"
ORG_NAME = "P2"