name = "cloudflare-wallet-app-user"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "canton-wallet-auth"
database_id = "bab93e48-202f-4a10-bf68-eb30fb2d2824"

[vars]
SPLICE_HOST = "p1.cantondefi.com"
SPLICE_PORT = 443
CANTON_JSON_HOST = "p1-json.cantondefi.com"
CANTON_JSON_PORT = 443
CANTON_AUTH_SECRET = "unsafe"
CANTON_AUTH_USER = "ledger-api-user"
SPLICE_ADMIN_USER = "app-user"
CANTON_AUTH_AUDIENCE = "https://canton.network.global"
RP_ID = "P1"
RP_NAME = "P1"
THEME = "purple"
ORG_NAME = "P1"
CHAT_AGENT_WEBHOOK_URL = "https://manage.uranus.im/api/agents/default/webhooks/21fe6eaa-ad83-4601-8780-828c21aa9db4"